// Autogenerated Verilog visualisation types file, this should not be edited manually

package verilatorVis;

typedef struct packed {
	logic[31:0] rd_data_padding_bits;
	logic[31:0] rd_data;

	logic[62:0] rd_valid_padding_bits;
	logic[0:0] rd_valid;

} read_dvis_t;

typedef struct packed {
	logic[31:0] wr_data_padding_bits;
	logic[31:0] wr_data;

	logic[62:0] wr_valid_padding_bits;
	logic[0:0] wr_valid;

} write_dvis_t;

typedef struct packed {
	read_dvis_t read;
	write_dvis_t write;
} fifo_vis_dvis_t;


endpackage
